name: lazy_flutter_helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.3
  data_connection_checker_nulls: ^0.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fzregex: ^2.0.0
  http: ^1.2.1
  intl: any
  responsive_framework: ^1.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/audios/

flutter_gen:
  assets:
    package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
